# Generated by Django 6.0.4 on 2026-04-24 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceActorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('zh', 'Chinese')], default='en', max_length=10)),
                ('category', models.CharField(choices=[('corporate', 'Corporate'), ('commercial', 'Commercial'), ('audiobook', 'Audiobook'), ('animation', 'Animation'), ('elearning', 'E-Learning')], default='corporate', max_length=20)),
                ('price_per_word', models.DecimalField(decimal_places=3, default=0.01, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
