# Generated by Django 6.0.4 on 2026-04-24 11:59

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactorprofile',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.audio_upload_path),
        ),
    ]
