# Generated by Django 6.0.4 on 2026-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_voiceactorprofile_audio_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceactorprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('zh', 'Chinese')], default='en', max_length=10),
        ),
    ]
